/* ============================================================
   BARBAULT.JS — os doze signos segundo André Barbault,
   "Manual Prático de Astrologia" (capítulo dos signos).
   Texto fiel à edição portuguesa, apenas limpo de artefatos
   de digitalização; cortado antes dos exemplos históricos.
   ============================================================ */
const BARB_SIGNO={
 0:`Simbólica: Simboliza o fogo original que se manifesta à entrada da Primavera, o jorrar das forças brutas da vida (desabrochar dos botões, saída dos rebentos da terra, cio dos animais...). Sob este signo, o ritmo vital é o dum salto em frente, duma aceleração: começo, renovação, propulsão, impulso, jacto, rebentamento, explosão... É o sopro do fogo prometaico, esse fogo criador e ao mesmo tempo destruidor, cego e generoso, caótico e sublime, icapaz de explodir em todas as direcções; é a descarga irruptiva, fulgurante, indomável do raio; a violência indiferenciada do fogo lanimal; a irrupção anárquica, devoradora, de instintos primitivos vigorosos; uma libertação de forças novas, inclassificáveis e inadaptadas, de promessas generosas, voltadas para o seu desenvolvimento.

Esta natureza é de essência marciana. Representa antes de tudo 2 luta pela vida no estádio da selecção natural em que reina a lei do mais forte. Mas, com o grito de guerra agressivo e os ímpetos de cólera e de desejos de Marte, aparece a exaltação solar simbolizado pela vitória dos dias sobre as noites, do calor e da luz. Com a assinatura Marte-Sol, o Carneiro é o signo mais masculino, o que Corresponde ao animal-tipo (carneiro) que é um hipermacho.

Psicologia; O factor dominante da estrutura psicológica do tipo Carneiro é a primaridade, que é como que uma presença do ser todo empenhado no instante, e daí todo um comportamento geral: Teacções fortes, imediatas e breves; impulsividade, mobilidade e fugaCidade das impressões; amor da mudança, da novidade; instabilidade,

indisciplina, precipitação, entusiasmo, cabeçadas; espontaneidade, improvisação, fervor, exaltação, paixão, extravagância, política do «tudo-ou-nada», estados paroxísticos... Há que acrescentar que, à imagem do animal cuja força está toda concentrada na massa craniana à frente, este Primário projecta-se para o futuro, que aborda com um certo poder de choque (daí a relação do Carneiro com a cabeça): vive de projectos, lança-se em aventuras, semeia mas muitas vezes deixa os outros colher...

A Primaridade associa-se nele à Actividade e à Emotividade, o que faz dele um Colérico bastante puro. Muitas vezes chega a ser sobreemotivo; a Actividade é o coeficiente mais modificável. A inteligência é do tipo Intuição (introvertida ou extrovertida).

Dialéctica: Não há dois tipos de Carneiros dialécticos, pois o ser deste signo é feito de uma só peça, simples, franco, directo, puro, total em faco de si mesmo e dos outros. Podemos, quando muito, assinalar que, se tende normalmente para a extroversão, certas influências exteriores podem voltá-lo para a introversão (oposição típica dos Carneiros Zola e Baudelaire).

Destino: Predisposição para a aventura, os acidentes, as lutas, combates, rivalidades, processos, gastos excessivos, amores à primeira vista, paixões repentinas, devoradoras; tendência para a vida ruidosa, instável, palpitante, febril, para os excessos e as desordens; propício à afirmação duma personalidade para traçar um caminho novo, desempenhar um papel de guia, de inovador, de precursor, de chefe.`,
 1:`Simbólica: Simboliza na natureza a condensação do ímpeto do Carneiro, a materialização das forças criativas que se concretizam na abundância das formas, sendo esta segunda parte da Primavera à da vegetação maciça, dos relvados viçosos, das verdes pastagens, da flora, da subida das essências vegetais e do aparecimento dos primeiros frutos. À imagem do bovídeo, o ritmo novo é de lentidão é de estabilidade pelo peso, a espessura e a densidade da matéria. Mas esta encarnação é rica; assimila-se à terra nutriente, à mãe-natureza, fecunda por excelência. Trata-se, de resto, do signo mais feminino, à imagem da vaca, animal hiperfêmea.

A sua natureza é de essência venusiana: é a paz, a alegria de viver no inebriamento dos sentidos, dos valores duma Vénus carnal, toda plena e vibrante de emanações terrestres, a Vénus Génitrix. A Lua, pela sua Exaltação no signo, participa também desta matureza: a substância em toda a sua fecundidade está entregue ao seu poderde acção produtiva.

Psicologia: A peça-chave da estrutura psíquica do Touro é a secundaridade, representada pelo boi de formas planturosas, com a força toda acumulada no cachaço (analogia que associa o Touro ao pescoço), que, perseverante lavrador, traça o seu sulco sem pressa, num esforço paciente que vence as resistências. O ritmo do: volante interior da secundaridade leva este tipo a ficar muito tempo sob o impacte da impressão recebida, conservando a sua marca; esta deixa-lhe marcas profundas que cavam um pesado sulco nas profundezas do seu ser, que, através do presente, ressente, repensa, remastiga o passado: é um «ruminante» psíquico. Daí a fidelidade, a constância, O apego, a resistência, a paciência, a adaptação lenta, a perseverança, a teimosia, o rancor, o remoer, a fixidez, a opiniosidade, a força estática, a força maciça e concentrada.

É também um instintivo, um ser são, em contacto directo com a natureza universal. Os seus instintos são imperiosos, sensualidade transbordante, bem instalada no real por um capital de saúde que pode embrutecê-lo num egoísmo confortável. Os seus instintos são essencialmente captativos: captam, absorvem como raízes no solo. Assim, este tipo é sobretudo um instintivo oral, cheio de cobiças digestivas, com tendência para engordar, engolir, assimilar, adquirir, possuir, conservar, viver o mais intensamente possível no mundo

do ter. A exaltação da vida é vivida no modo sensorial e faz dele um dionistaco: encantos terrestres, grandes volúpias, amor à terra, à natureza...

Dialéctica: O tipo Touro oscila entre dois pólos extremos. De dominante fria (Saturno-Lua), e à imagem do pesado boi ou da vaca a pastar tranquilamente, dá um lento de temperamento linfáticonervoso, vagotónico entorpecido pela passividade vegetativa, um tanto ou quanto pesado, não emotivo, de carácter plácido, tranquilo, monótono, propenso à taciturnidade, à melancolia « ao pessimismo. De dominante quente (Marte-Júpiter-Sol), à imagem do touro na arena, dá um expansivo de temperamento sanguíneo, hiperemotivo e activo lançado à velocidade do volante, optimista, excitável, de cóleras temíveis, propenso às paixões fortes, aos excessos e explosões do instinto, Os dois opostos podem coexistir.

Destino: Segundo um ou outro caso, a vida é calma ou tempestuosa. Este tipo tem tendência para se fixar na paixão do trabalho, do dinheiro ou do amor. Construtor e estabilizador, está predisposto a dedicar-se ao labor, às grandes tarefas, num esforço intensamente construtivo; possessivo, volta-se para a aquisição de bens materiais, para o enriquecimento; senão, grande consumidor, pode embrenhar-se na senda do prazer ou nas grandes paixões do amor, volúpias, ciúmes e tempestades passionais.
iquecimento; senão, grande consumidor, pode embrenhar-se na senda do prazer ou nas grandes paixões do amor, volúpias, ciúmes e tempestades passionais. Catarina de Médicis é um caso representativo do Touro, com a presença do Ascendente, do Sol e de Vénus regente no signo, um Touro cuja dominante Saturno-Capricórnio reforça a secundaridade do signo. Todos os seus biógrafos notam nela a resistência, a perseverança, a paciência dos obstinados a quem nada faz desistir. Fazendo uma longa aprendizagem na corte de Francisco I a que tem de adaptar-se, nada a desanima, nem as humilhações de Diane de Poitiers nem a indiferença do marido, o futuro Henrique IL. Dedicando ao infiel um estranho apego, uma fria expectativa fá-la-á saborear a hora em que o seu ódio acumulado contra a favorita explodirá como um furacão. A pesada florentina, embaraçada nos seus crepes e vestido fúnebre, irá confinar-se numa viuvez austera. Afirmando-se pacientemente na corte depois de ter vencido o seu despeito, ultrajada e desprezada durante tanto tempo, vêmo-la alçar-se a passos contados ao govemo de Francisco IT, e depois à regência que lhe confere a minoria de Carlos IX.
prezada durante tanto tempo, vêmo-la alçar-se a passos contados ao govemo de Francisco IT, e depois à regência que lhe confere a minoria de Carlos IX. A paixão capricomiana-saturnina do poder afirmando-se como uma ambição suprema da sua vida, será com extrema obstinação que defenderá a unidade da monarquia. Lutará vinte e cinco anos para desmentir os seus astrólogos, que lhe predisseram o advento dos Bourbons, e não se Tesignará a consagrar o fracasso dos seus esforços. Aos sessenta anos, apesar duma obesidade pronunciada (traço taurino, como a sua gula) e da gota, percorre a França de cidade em cidade, de castelo em castelo, durante dezoito meses, com as maiores dificuldades e, até

às vésperas da morte, ainda tece as suas teias de aranha para impor a sua autoridade a Henrique III.`,
 2:`Simbólica: Simboliza na natureza, após a eclosão do Carneiro e a encarnação do Touro, a conquista aérea da vegetação pela ramagem e a folhagem, sendo esta terceira parte primaveril a da plenitude da função clorifiliana, em correspondência com o aparelho pulmonar, sede da função respiratória, e com os membros superiores, órgãos da motilidade. Tudo é dualidade neste signo de Ar bipolar: os dois braços, os dois lobos pulmonares, aspir e expir, os dois pauzinhos verticais do seu ideograma, os Dioscuros, Castor e Polux, do símbolo. É também o signo dos ritmos rápidos e dos movimentos rápidos, das relações estreitas com o meio ambiente bem como com a vida do espírito.

Quanda o Carneiro é hipermacho e o Touro hiperfêmea, os Gémeos são andróginos, signo da polarização, da diferenciação dos dois princípios opostos e complementares. À sua natureza é da essência adolescente, hermafrodita de Mercúrio, princípio de ligação, de trocas, de movimento, de adaptação, de comunicação, de interpenetração, de cerebralização. À

Psicologia: A propriedade predominante do signo é a primaridade associada à amplitude do campo de consciência, dando o «superficial largo» de Otto Gross, que com isso entende essa Jargueza virtual que dá à consciência uma grande mobilidade, pois só projecta a cada instante nas coisas um fino pincel de atenção sem insistir na captação dessas coisas; daí um fraco vestígio de impressão, pois 0 pincel da atenção varre aqui uma larga superfície de tepresentações. Se o Carneiro é o mais impulsivo dos signos e o Touro o mais fixo, os Gémeos são o mais móvel. É um nervoso que não pesa mais do que um fio e vive no or; um rápido de humor cambiante, um mutável, amante do movimento, remexido, feito para o desapego. É também, roscau pensant, um maleável, um flexível, ligeiro, hábil, adaptável, epidérmico; Arlequim jogando a sua vida ou vivendo o seu jogo, comediante, camaleão, topa-a-tudo, esperto e por conseguinte instável, ligeiro, ao mesmo tempo em toda a parte e em parte nenhuma, Vítima da divisão interior e dos problemas que esta levanta.

Dialéctica: A Primaridade combina-se de duas maneiras opostas na perspectiva caracterológica, e daí dois tipos possíveis:

a) O tipo Castor Emotivo-subactivo, correspondente ao Nervoso; sensibilidade instável, sempre em movimento, viva75

cidade de sentimentos, em busca de emoções novas, vagabundagem afectiva, vida sacudida por impulsos sucessivos, paixões desconexas e inconstantes; ser fantasioso, vivendo numa atmosfera febril e buscando um «presente» tão intenso ou deslumbrante quanto possível;

b) O tipo Polux subemotivo-aotivo, correspondente ao Sanguíneo, espécie de «espírito sem alma» senhor duma grande presença de espírito, vivendo e agindo segundo o que pensa, curioso, prático, hábil, oportunista, inventivo, irónico, espirituoso, de coração seco.

É frequente estes dois caracteres opostos alternarem ou coexistivem em dois planos diferentes no mesmo sujeito, mas geralmente um dos dois predomina.

Destino: Possibilidade de dispor de vários recursos e predisposição para seguir um itinerário com destinos diversos, ou mesmo para seguir vários caminhos paralelamente. Possibilidade de alcançar êxito pelo virtuosismo, sobretudo pelo jogo das relações, em particular para escrever, falar, adaptar, transmitir, interpretar, traduzir, trocar ou deslocar-se... Vida bastante instável e itinerante, à espreita ds aventuras ou experiências novas.`,
 3:`Simbólica: Simboliza na natureza o primeiro estádio do Verão que corresponde à formação das sementes e marca o triunfo das forças geratrizes matemas. Concepção, gestação, maternidade, tal é o processo canceriano no seu contexto alimentar, digestivo, formador (corresponde ao estômago e aos seios). Simboliza igualmente a água original, as águas-mães, no momento do ano em que a seiva vegetal infla os tecidos da natureza em plena fecundidade, O crustáceo (camarão ou caranguejo) que o representa é particularmente prolífico: vive debaixo duma carapaça como os germes, ovos, fetos é rebentos, esboços e prefigurações da vida renascente (concha, matriz, casca, invólucro); caminha às arrecuas, símbolo dum retrocesso, dum, refluxo para o seu passado.

Esta natureza é de essência lunar, sendo a Lua o símbolo da mãe o da criança, da água, do crescimento, da alimentação, da fecundidade, da vida vegetativa, instintiva, crepuscular, inconsciente...

Psicologia: O complexo maternal constitui a trama da psique deste tipo, que está próximo da sua sensibilidade cenes! ésica, da. sua vida vegetativa; dá a impressão de se demorar na infância, de viver dentro da sua concha, de se refugiar no seu passado. Assim, tem tendência. para se identificar com a mãe, para se apegar à família, à infância, às recordações, preferindo o dentro ao fora, o interior ao exterior, o íntimo ao social. É um sonhador, um sentimental, um sensível, um imaginativo, inclinado para a esquizoídia, o autismo, a submissão passiva e feminina, primeiro à mãe & depois ao mundo.

É um sobreemotivo-subactivo em quem a inactividade: desvia à emotividade da acção sobre as coisas para as reduzir à consciência de si, voltando-se o ser para as paragens interiores. É ao mesmo tempo um introvertido, um Narciso, contemplativo, lírico, reduzido ao sentimento da sua pessoa, sonhando a sua vida ou vivendo o seu sonho. É também um elegíaco, um romântico que tem o amor do maravilhoso, do fantástico, da magia.

E Charles X,t. 2, por P. DE LA GORCE, Plon, 1928.

Por vezes, sob a influência dum aspecto saturnino ou uraniano, este tipo opõe-se por defesa à influência materna; é a reacção, seca € fechada, contra tudo o que é feminino, afectivo, emotivo, irracional, instintivo...

Dialéctica: Conforme prevalece a secundaridade ou a primaridade, o Canceriano dá um:

a) Sentimental-paranervoso: Ser de emotividade um tanto recalcada, que se exprime em ruminações dolorosas, em meditações, deixando mais ou menos de viver para se sentir viver. Indeciso, veleitário, inibido, resignado, melancólico, propenso à auto-acusação, à misantropia; predominância dos sentimentos morais; apego às recordações, ao passado, aos hábitos; interesse pela história;

b) Nervoso-para-sentimental; Ser entregue à contradisão dos seus entusiasmos sucessivos, inclinado para a mudança, a renovação das sensações; caprichoso, vagabundo afectivo, indo duma coisa para a outra, infiel ao objecto mas sempre agarrado às imagens dum Eu sensível e susceptível.

Destino: Apresentam-se, pois, dois tipos de destino diferentes:

Um é dominado pelo humor sedentário s voltado para uma vida estável. É a alma simples, a natureza bonacheirona, tranquila, familiar, caseira, sem paixões aparentes. O ser é feito para a vida de interior; mexendo-se pouco e fixando-se, é agarrado à família, à casa, à terra, às suas quatro paredes como às realidades materiais.`,
 4:`Simbólica: Simboliza na natureza a culminação vegetal, a plenitude do fruto, toda a magnificência ou maturidade sob o mais brilhante sol do ano. Em analogia com este apogeu dos meios-dias de Verão, é o signo da plena afirmação da individualidade, da vontade, da consciência, do «Eu», da soberania egocêntrica, Se o fogo cardinal do Carneiro é animal, cego e sublime, o fogo fixo do Leão é a expressão duma força dominada, duma energia-luz disciplinada, dum fogo individualizado, consagrado aos poderes do Eu, da vontade dirigida, força central reguladora e radiosa de vida, de calor, de luz e de brilho. E a q Signo solar, em analogia com o coração, é, «rei dos animais», da natureza do astro central e sublime, simbolizando o que é régio na vida psíquica, o que tem de mais nobre o instinto. Mas, quando o Leão encarna muitas vezes na forma inferior do animal cego pelas forças que não pode domar, o Sol, personificador da vida adulta, socializada, policiada e sublimada, nas suas altas sínteses, é susceptível de desempenhar o papel dum superego tirânico, Tesponsável pelas piores crises internas.

Psicologia: O leonino é uma força da natureza, muitas vezes de constituição atlética e ainda mais vezes animada por um temperamento bilioso. Um forte, são, que vai ao encontro da. vida, confiante, feliz, natural, com uma abundância vital que lhe dá aprumo, envergadura, certeza, audácia, uma sede de conquista, de domínio, de ambições. É um Apaixonado (Emotivo-Activo-Secundário): impulso do Eu, expansão vital até à hipertrofia tirânica da vontade, sentimento de grandeza, falta de simplicidade, orgulho, sobrestimação de si próprio, necessidade de prestígio, carácter magnânimo, altaneiro, tecto; ambição realizadora visível, mobilização das forças íntimas na mais alta tensão interior, ao serviço duma paixão principal, dum ideal dominante que se torna a alma da sua vida, o centro da sua existência; sentido do mando, do poder, das responsabilidades. Risco de inflação do Eu, muitas vezes na identificação com a sua profissão, o seu título, a sua missão... com exibicionismo, máscara social a devorar a individualidade, sendo o ser meio glorioso meio escravo, actor que só existe pelo seu público, dando um valor especial ao facto de ser olhado, apreciado, admirado...

Dialéctica: Podem distinguir-se duas orientações particulares do leonino:

a) O Hercúleo; o poder exerce-se no alargamento horizontal e dá o realista; é um físico, forte, vixil, combativo, voltado para a grandeza material, vivendo com a preocupação empírica do terrestre que lhe impede toda a sublimação (dominante marciana, jupieriana);

b) O Apotineo; o poder amima-se na tensão vertical e dá um ideausta. Homem de a: ao, é heroi da honra; ariista, é discipunado pelo seu sol imermor que raz remar indavisos 08 poderes luminosos da beleza ordenada, da arte dominada: a perteição é os esplendores zemtais. O seu êxito condu-lo à grandeza espiritual (dominante solar, saturmna, uraniana).

. Destino: Coeficiente elevado de êxito em razão da aptidão para «ficar com a parte do leão» pela afirmação do eu e dos interesses pessoais. Um dos seres mais bem colocados para construir uma tortuna e para satisfazer o seu amor da vida luxuosa, opulenta, taustosa. Dotado para lidar com grandes negócios, construir empresas de grande envergadura, alçar-se à postos elevados, ao poder, ter uma política de prestígio, realizar conquistas imperiosas que satisfazem ambições importantes. É feito para a. vocação e para função pública.`,
 5:`Simbólica: Simboliza na natureza o termo dum longo processo: semeada no Capricórnio, a semente dá aqui a espiga madura, pronta a ser ceifada; é a ceifa, o armazenamento. Sob este signo de Terra=Mutável, estéril por algum tempo, na natureza tudo seca (a semente Solta-se da espiga soltando-se do seu invólucro), tudo se diferencia, Se selecciona, se particulariza, se delimita, se reduz, se submete a limites precisos. O impulso vital está no declínio, as forças diminuem, às formas reduzem-se; mas o empobrecimento da vida bruta é comPensado por uma ordem do espírito: é o aparecimento da razão, Procurando o homem a sua medida na lógica. A energia canaliza-se

ANDRÉ BARBAULT para a esfera imaterial da inteligência, para a acuidade do espírito. Este signo corresponde organicamente ao intestino na sua função de rede de triagem, de assimilação e de eliminação dos dejectos. Signo de Mercúrio, está em afinidade com o astro na repressão da vida sensível, na intelectualização e na socialização a favor dos usos e das convenções submetidos às regras do bom senso; comércio da espírito pelas ideias vestidas de palavras e comércio da matéria pelo sistema das trocas regulamentadas. O signo e o planeta estabelecem distinções, separações, demarcações, classificações, como a secura separa as partes dum todo, Psicologia: É um temperamento nervoso no qual a vida psíquica e mental passa à frente das manifestações físicas, uma natureza. refinada, de reacções desligadas, de comportamento selectivo, com certas dificuldades de adaptação e de integração na vida ambiente, com uma inquietação latente. A recusa do instinto está na base da personalidade: o ser passa tudo pelo crivo, reflecte antes de agir, chega a ser minucioso de mais. Graças a este travão, introduz na sua vida uma disciplina e edifica uma ordem que satisfaz um ideal.
cte antes de agir, chega a ser minucioso de mais. Graças a este travão, introduz na sua vida uma disciplina e edifica uma ordem que satisfaz um ideal. Daí um lado perfectível, um desejo de cultura ou de perfeição moral que satisfaz uma necessidade de autodeterminação, de segurança de si Perante a inquietação do desconhecido, prefere apoiar-se nas passadas sensatas do seu juízo, colocando a sua salvação num plano reflectido, num cálculo raciocinado, num acto aperfeiçoado. Prático, realista, busca a segurança, a quietude, vive tomando medidas de defesa contra O instinto com mecanismos de protecção sob a forma de retracção do Eu (introversão, reserva, pudor, timidez, sobriedade, sentimento de inferioridade, desapego...). Corresponde ao complexo anal recalcado da psicanálise freudiana: tendência geral para reter, controlar, disciplinar-se, dominar-se; economia, parcimónia, acumulação, conservação; temporização, criação laboriosa no escrúpulo, a mania do pormenor, o apego aos princípios, as regras e as normas; honestidade, consciência, seriedade, aplicação, respeitabilidade, pureza, perfeição; análise, dúvida, cepticismo, lucidez, organização, método, classificação, sistematização, gosto enciclopédico; espírito voltado para as coisas difíceis, laboriosas, ingratas ou penosas.
z, organização, método, classificação, sistematização, gosto enciclopédico; espírito voltado para as coisas difíceis, laboriosas, ingratas ou penosas. Dialéctica: Neste tipo, a inibição vence geralmente o impulso, mas, em consequência duma dominante planetária particular (marciana, plutónica entre outras), esta relação inverte-se, de modo que temos o complexo anal relaxado que corresponde aos valores Escorpião: natureza instintiva, indisciplinada, revoltada, desordenada, agressiva, anticonformista, autoritária, teimosa, destrutiva, sádica... Existe muito mais frequentemente uma alternância ou uma coexistência da inibição e da impulsividade, de modo que o tipo Virgem corresponde ao tipo ambivalente: racional e irracional,

MANUAL PRATICO DE ASTROLOGIA económico durante um certo tempo e subitamente gastador, pontual e inexacto, maníaco e desordenado, céptico e supersticioso, crítico e criativo, atarefado e fecundo (em tempos sucessivos)... e nos casos extremos e segundo as circunstâncias, recatado e devasso, polido e hipócrita, preocupado com a etiqueta e desbragado, timido metendo os pés na travessa, ingénua Lbertina, neurotico-perverso.., Destino: Tem a tentação de jogar a sua vida num jogo mais pequeno do que ele; conta menos insucessos que os outros tipos mas mais resultados medianos. A Virgem é um instrumento, um poder de domínio que pode ser posto ao serviço duma grande paixão. Mas, sozinha na acção, tende a contentar-se com pouco, com um êxito modesto, por não se salientar, por culpa duma vida muito direita ou à margem da grande vida, Assim, este tipo tem gemalmente uma situação abaixo do seu valor real. Para ele o que conta é a necessidade de sex útil, o gosto de servir, a paixão do trabalho, o dom ao seu ofício.
uma situação abaixo do seu valor real. Para ele o que conta é a necessidade de sex útil, o gosto de servir, a paixão do trabalho, o dom ao seu ofício. ma fácil reconhecer a Virgem nos grandes administradores que fizeram teinar o trabalho, a ordem e a disciplina, Richelieu (Sol e Mercúrio no signo) dedicou a sua vida a um combate (Escorpião) no desígnio de regular, disciplinar e organizar todas as forças nacionais sob a férula do princípio monárquico. O continuador de Richelou, Mazarin (de quem veremos mais adiante que o Saturno-Escorpião dominante é um análogo da Virgem), transmitirá a Luís XIV as condições duma era de glória e de prosperidade, deixando-lhe uma equipa de colaboradores e um método de governo. O lado Virgem — que representa apenas um aspecto do seu ser, recordemos que é a regra neste capítulo em que só se examina um único signo a propósito de tal personagem — é visível neste grande rei que, como Richelieu, tinha o Sol e Mercúrio no signo, e que arrematou a sua obra. Com efeito, reina nele a paixão da ordem, até aos mais ínfimos pormenores, servida por uma assiduidade e uma exactidão na sua conduta. Controla os ministros do seu conselho uns através dos outros, exigindo-lhes um relatório fiel e frequente.
assiduidade e uma exactidão na sua conduta. Controla os ministros do seu conselho uns através dos outros, exigindo-lhes um relatório fiel e frequente. Por toda a parte passeia o seu olhar, encarando todas as coisas de alto e ao mesmo tempo de perto, combinando as duas qualidades contraditórias, a paixão do grande nos seus planos (Sol-Júpiter) e a minúcia na realização. É, segundo a feliz expressão de Saint-Simon, «o rei das abelhas» cujo trabalho vigia e distribui. Faz reinar na corte uma minuciosa etiqueta, regida por uma hierarquia extremamente comPlicada. Tudo reside no cerimonial. Mas esta disciplina constitui a Própria essência da sua natureza, a sua vida está regulada instante por instante. Pode até ver-se a assinatura da Virgem em certos incómodos de saúde de que o rei sofreu: obstipação, enterite, vermes

ANDRB BARBAULT
ANDRB BARBAULT intestinais... Enfim, não é descabido estabelecer uma associação entre o aspecto cultural do signo e o excepcional florescimento das letras e das artes que confundiu o seu reino com a culminação do Classicismo. O reinado deste grande rei deveu a verdadeira base da sua grandeza à rigorosa administração do Virgem-satumino Colbert (Ascendente-Sol-Mercúrio no signo), homem de trabalho (trabalhando dezasseis horas por dia num trabalho assíduo, pôs a França a trabalhar), da economia (sabe-se que não teve medo de refrear constantemente as prodigalidades do faustoso Rei-sol), da ordem e da austeridade: criador do «Estado de previdência», origem do orçamento, manda redigir um código de comércio, interessa-so pelos ofícios, desenvolve a agricultura, a indústria e o comércio, regulamenta severamente a manufactura, abrindo caminho ao corporativismo e à estandartização (Colbertismo), sem negligenciar (nada escapa ao seu controle) à reorganização dos serviços públicos, a codificação das leis, a fundação das academias e bibliotecas. Assim como, na vida privada, Richelieu foi um grande coleccionador de quadros, Colbert foi um grande coleccionador de manuscritos e de livros preciosos, e possuidor duma biblioteca raríssima.
i um grande coleccionador de quadros, Colbert foi um grande coleccionador de manuscritos e de livros preciosos, e possuidor duma biblioteca raríssima. Em Francisco 1, o Sol (conjunto com Júpiter) na Virgem é um parente pobre, pois todas as suas dominantes planetárias e o resto do seu céu vão contra as tendências deste signo. Contudo não poderíamos desprezar o papel (Virgem forrada de Gémeos) que tem a vida do espírito na existência e no reinado deste príncipe. Sabemos a curiosidade intelectual deste soberano letrado que situava a poesia entre as suas actividades privilegiadas, versejador distinto que tratava os escritores como confrades, e se apaixonou pelas artes e as letras a ponto de ter sido o primeiro soberano desde Carlos Magno que se interessou ardente e eficazmente pelos problemas da cultura.
pelas artes e as letras a ponto de ter sido o primeiro soberano desde Carlos Magno que se interessou ardente e eficazmente pelos problemas da cultura. É com razão que Brantôme lhe: chama o «pai e restaurador das letras e das artes», e é oportuno lembrar que é o criador do Collêge de France, Podemos até estabelecer um paralelo: tal como o reinado do Virgem Luís XIV se confunde com o brilho sem par do Classicismo, o de Francisco I participa da grande corrente de civilização do Renascimento, confundindo-se a juventude do rei com a do seu século, a ponto de podermos chamar-lhe o século de Francisco I como se fez com Péricles e Luís XIV. Quanto a Luís XVI, Virgem pelo Ascendente, o Sol, Mercúrio e Marte, Tepresenta o signo reduzido a si mesmo, sem socorros exteriores perante as suas dissonâncias: carácter honesto, consciencioso, meticuloso, escrupuloso, tímido, irresoluto, timorato, besitante, económico... rei artífice manejando durante horas a. lima do serralheiro e a pinça do relojoeiro.`,
 6:`Simbólica: Simboliza na natureza o equilíbrio dos dias e das noites, marcado pela ascensão do mundo nocturno igualada pelo declínio do mundo diurno que é o da luz e do calor (queda do Sol). Os últimos frutos soltam-se das árvores; é a prefiguração duma era. de repouso, de desanuviamento, de paz, onde as formas exteriores se apagam progressivamente ante a vida interior. Este crepúsculo outonal da natureza está em dialéctica com uma aurora da alma simbolizada pela exaltação de Saturno, valorizando as tendências para o desapego, o despojamento, a renúncia, vitória do espiritual sobre o material, O símbolo (os dois pratos igualados da balança) significa tanto uma relação de equilíbrio entre dois alternantes, uma oposição dos contrários como uma associação dos complementares. No oposto do Carneiro, brutal, agudo, quadrado, é o signo da médi da medida, dos meios tons, dos cambiantes; é um signo de Ar de natureza subtil e etérea, sob a tutela de Vénus a pacificadora, a Vénus-Afrodite das rosas do Outono, ordenadora celeste do amor, do belo, do justo, inspiradora das artes.

Psicologia: A natureza deste tipo constrói-se no equilíbrio de dois temperamentos opostos: um nervoso (Saturno) delicado, fino, evadindo-se da matéria ou depurando-a, e um sanguíneo (Vénus) todo atmosférico, destinado a realizar-se pelas suas trocas, feitas de fluidez, com o meio ambiente. É a conjunção do dom venusiano da juventude e o esgotamento saturnino da vida: nervoso expansivo ou sanguíneo tendo perdido a sua riqueza plástica. O ser inclina-se, pois, alternadamente para a espontaneidade e a meditação, o abandono e o receio, o apelo e o recuo perante a vida... Natureza do «justo meio», propensa aos compromissos, concessões e meios termos, mas também às posições mornas e às atitudes de meias tintas. Ponderação, tolerância, pacifismo, sentimento de equidade. Carácter social, adaptável, por vezes oportunista, amável, delicado, gracioso, harmonioso, mas vontade fraca, desarmada pela indecisão e a hesitação entre duas ss ções opostas como pelo desejo de agradar. Disposição mais efeminada que viril em detrimento da vontade de poder e em benefício do requinte estético ou espiritual.

Dialéctica: Este tipo dá, segundo a predominância de Júpiter ou de Saturno, do Sol ou da Lua:

a) O Sentimental extrovertido: Desabrocha simpatizando e expandindo-se: sente-se agarrado ao mundo pot toda uma rede de laços, de afeições, e dá livre curso aos impulsos generosos que o lançam nos braços dos outros,

pois o seu sentimento anima tudo aquilo que toca pelo seu calor comunicativo. Sabe conquistar os corações e cativar as pessoas; este hospitaleiro é de um acolhimento espontâneo que se abre em leque a todos os que o rodeiam, a todo o meio, próximo ou afastado, ao qual se agarra e se abandona;

b) O Sentimental introvertido: De extensivo, o sentimento torna-se intensivo; concentra-se numa única pessoa em vez de se dispersar com graça. Se tem mais intensidade, também tem mais fragilidade pela inquietação em que faz viver; pode retirar-se para evitar a rudeza do exterior. O carácter tem a sua reserva, o seu silêncio, com uma igualdade de humor que lhe confere uma calma agradável, mas esta superficie aparentemente tranquila não deixa de cobrir paixões agudas duma sensibilidade mais ou menos dolorosa.

Destino: Carece de agressividade conguistadora, o que o põe em desvantagem na luta pela vida e não o leva a fazer fortuna. É da raça dos sensíveis, dos requintados que constroem para si uma existência agradável e harmoniosa, à margem das grandes cobiças terrestres e onde os valores do «ser» têm a propriedade sobre. os valores do «ter». É mais bem sucedido particularmente pelo seu sentido associativo e cooperativo, numa colaboração, e sofre fontemente a influência conjungal, boa ou má.`,
 7:`Simbólica: Simboliza na natureza O fim da vegetação, a queda e a decomposição das folhas, expressão da destruição dos valores objectivos é das formas exteriores, em favor dum processo de fer3 Note-se que sofria do crises de cólicas hepáticas.

ANDRH BARBAULT

mentação, de putrefacção, de desagregação. Este signo de Água-Fixa é o da água imóvel e fétida dos pântanos, como o da aguardente ou da lava vulcânica. No oposto do Touro, que corresponde aos valores captativos e aquisitivos da boca, é o do ânus, que corresponde psicanaliticamente aos valores de excremento: dejecção, expulsão, liquidação, restituição; transforma, destrói, corrompe, recompõe... Mas se corresponde ao ânus com a sua carga de pulsões agressivas, corresponde também ao sexo com o seu poder criador, fecundante. Este signo está sob a tutela de Marte e de Plutão, o «príncipe das trevas», símbolo das profundezas e das trevas da nossa noite original, sobretudo das nossas regiões infernais.

Psicologia: Esta natureza de temperamento bilioso é trabalhada por um fogo interior, animada ao nível das entranhas pela exasperação de pulsões violentas. Este «diabo no corpo» exprime uma angústia de viver, uma sede de mais-ser mais do que do bem-estar, que procura as suas afinidades nas tempestades e convulsões da vid Dois grandes instintos se confrontam numa ambivalência intensificadora: a agressividade e o erotismo; dança endiabrada do sublime e do abjecto, do céu é do inférno, do realismo brutal e do idealismo místico, do apego e do desapego, do amor e da morte. O instinto sexual prolonga-se sob o aspecto criativo: dom de produzir, de fecundar, de realizar num fluxo irresistível; o poder do ser é o que vem do sexo, e é por este poder sexual, natural, deslocado ou sublimado, pela integração do erotismo, bruto ou espiritualizado, que encontra a sua razão de ser. Na dissonância, o ser é inquieto, atormentado; a sua alquimia interior destila os venenos dos estados mórbidos sentimentos do 'absundo, do nada, ideias de morte, nojo do angústia, sado-masoquismo, culpabilidade, autopunição, fobia, neurose. obsessiva...

Dialéctica: Neste tipo, a impulsão passa naturalmente à frente da inibição mas, em consequência duma dominante planetária pa cular (saturnina, por vezes uraniana), esta relação inverte-se, como o próprio complexo anal, inversão essa que faz do tipo Escorpião um tipo Virgem. Mais frequentemente, existe uma alternância ou uma coexistência da impulsão e da inibição correspondendo a um tipo ambivalente.

a) Complexo anal relaxado: Natureza individualista, rebelde, indisciplinada, revoltada, renitente a toda a coacção, refractária aos usos sociais, entregando-se aos seus instintos, capaz de dissipação, de intemperança, de desordem, de irritabilidade, de ódio, de vingança, de destruição, de sadismo ou de perversidade. «Um carácter», uma força de vontade, apaixonada, obstinada, autoritária, dura; poder de criação;

b) Complexo anal recalcado: Natureza contida, disciplinada, sóbria, ordenada, pontual, toda de consciência, de moral, de respeitabilidade, agarrada à regra, aos princípios, por vezes até à mania ou ao formalismo; mais crítico do que criador, laborioso, «obstipado», mais propenso à neurose do que à perversidade;

c) O ambivalente: tem de ver com estas duas naturezas opostas, o que se pode traduzir em fórmulas diferentes para cada caso (vide já o ambivalente Virgem): asseio físico e falta de asseio moral ou o inverso, vida burguesa e: opiniões cevolucionárias, amaneirado e desbragado, submisso e recalcitrante, formalista irritável, ordenado e desordenado, recatado e hipócrita, crítico e criativo, idealista e reptiliano, neurótico e perverso...

Destino: Sente-se bem (quando não é um tipo inibido) onde houver um perigo, um escândalo, um pesadelo, uma destruição... A sua vida é uma luta perpétua que lhe agrada, uma guerra ou um drama que se enlaça, desenlaça e se torna a reenlaçar. Pode ter uma ambição ilimitada, uma necessidade de poder que tende para o absoluto e muitas vezes se erige em máquina de guerra. A sua expansão é um turbilhão que gera uma certa desordem à sua passagem. A revolta, a morte, o mistério, o sexo, o dinheiro ou o sadismo, eis um dos temas ou o conjunto dos temas que moldam a sua vida.
ordem à sua passagem. A revolta, a morte, o mistério, o sexo, o dinheiro ou o sadismo, eis um dos temas ou o conjunto dos temas que moldam a sua vida. Luís XI é bastante representativo do Escorpião que está no seu Ascendente. Delfim, é um grande revoltado; aos dezoito anos é um rapaz terrível, indisciplinado, impaciente, ambicioso e duro. Quando rebenta a Praguerie (sublevação dos grandes feudais) está entre as fileiras dos revoltosos, e os descontentes chegam até a pôr o delfim à sua cabeça. Trava-se uma luta aberta entre o pai, Carlos VII, e o filho. Ao perdão do rei, o filho rebelde reage com uma resistência tenaz e com respostas impertinentes: «O rei governa-se o pior possível, mas eu tenciono pôr ordem nisso» A luta será recheada de episódios diversos: um estalo a Agnês Sorel, intrigas, conluios, conspirações... motivando o envio do delfim para o seu delfinato como medida disciplinar, e depois o seu banimento do reino com a ameaça de ser deserdado a favor do irmão. Foi por este tipo zodiacal não ter medo de se tornar antipático que os inimigos de Luís XI conseguiram forjar a lenda dum negro Escorpião manhoso, cruel, sádico (as gaiolas de ferro, as fillettes). Luís XI foi muito simplesmente um.
Luís XI conseguiram forjar a lenda dum negro Escorpião manhoso, cruel, sádico (as gaiolas de ferro, as fillettes). Luís XI foi muito simplesmente um. rei de carácter que, depois de ter tomado o partido dos feudais revoltosos, mostrou a mesma afirmação em. destruí-los (não há perdão para os traidores!); e foi graças a este combate de justiceiro implacável que deu à França um Estado forte.`,
 8:`Simbólica: A referência aos fenómenos da natureza é difícil com este signo pois, desde a provação do Escorpião, a vegetação já não existe. A energia saturnina opera uma projecção daquilo que: o Escorpião acumulou para o destinar a um fito. Nisso se justifica a imagem do centauro desferindo uma seta na direcção ascendente. Trata-se de ligar o próximo ao distante para fazer triunfar este sobre aquele, graças à união do inferior e do superior, dobrando-se o cavaleiro do poder do cavalo, fazendo corpo com o corcel, as pernas encostadas aos flancos (relação do Sagitário com as coxas no «Homem-Zodíaco»). O fogo sagitariano pode renunciar a servir (como no Leão) a magnificência do ego para atingir a experiência transindividual. E ao invés dos Gémeos, o signo oposto, que são dualidade e diferenciação, no Sagitário está o reino da, unificação, da reunião, da fusão, da síntese. Está sob os auspícios planetários de Júpiter, princípio de coesão, de coordenação, de globalização.

Psicologia: Na base desta natureza há um Eu em intensidade ou em expansão que procura os seus próprios limites e aspira a superá-los, como para atingir um «além do Eu». Daí uma aspiração a uma certa dimensão ou elevação que ele procura num transporte, quer este seja ímpeto de participação mo mundo, de integração na vida colectiva, revolta estimulante contra um poder a dominar ou simples inflação do eu que se perde em embriaguez de grandeza.

Dialéctica: As orientações extremas deste signo duplo são muito acentuadas:

a) Se o tema for harmónico, o sujeito tende para um conformismo confortável; adaptado, assimila as boas manei90

ras, conforma-se com os usos estabelecidos, é partidário da legalidade, da ordem, das convenções sociais. É um ser desabrochado, eufórico, com savoir-faire, tecto, leal, cavalheiresco, amante de prestígio e de honorabilidade;

b) Se o tema for dissonante, tende para a independência bravia, para a revolta. Por instinto, insurge-se contra a verdade do seu meio e comporta-se como um inadaptado e um insubmisso. A sua necessidade de emancipação passa à frente de tudo. Vontade insurreccional contra os hábitos, lugares-comuns e preconceitos; paixões imperiosas, ímpetos audaciosos, patadas fogosas de puro sangue...:

c) Se for extrovertido, é tentado pela aventura no seu encontro com o mundo; é um atleta, um desportista, de temperamento nómada, que tem acima de tudo a paixão das viagens, do explorador à espreita de horizontes novos, voltado para um sempre algures

d) Se for introvertido, o que predomina é a aventura no encontro consigo mesmo, ele procura esse além a que aspira em si mesmo, no alcançar das suas formas morais e espirituais mais elevadas. O seu entusiasmo dirige-se para o conhecimento, a cultura, a religião, a autoperfeição; visa um ideal, uma sabedoria no termo da sua viagem interior.

Destino: Segundo a primeira forma, é um móbil em perpétuas viagens, um aventureiro feito para as epopeias, as experiências de longo alcance. Segundo a segunda, tende para uma vida interior intensa que conduz a uma realização moral, filosófica ou espiritual.`,
 9:`Simbólica: Simboliza na natureza o despojamento, o enroscamento, O silêncio, a concentração do Inverno na sua severa grandeza. Signo de Terra-Cardinal, marca o estádio da semente enterrada no solo, início duma lenta maturação sem brilho em vista duma derradeira conquista a longo prazo. É ao mesmo tempo símbolo duma meia-noite celeste, apresentando-se o solstício de Inverno como um estádio de concepção, de raiz, de cepa (daí a relação com a estrutura interna das coisas), e dum meio-dia terrestre, que tem a sua réplica na Casa X no ciclo do dia, e enquanto tal dum cimo, lugar predilecto da cabra. Oposto ao Caranguejo, que é o signo da mãe, do berço, da encarnação e do íntimo como do supra-sensível, o Capricórnio tende para o impessoal, a desmaterialização, a libertação do terrestre. Nisso, é o signo de Saturno ao qual se junta (exaltação) Marte.

Psicologia: Este tipo é um frio, e a sua personalidade edifica-se num movimento de retiro em si e de concentração que exclui toda a exteriorização. Este «frio» é ao mesmo tempo introversão e inemotividade, real ou aparente (o «apaixonado a frio»), o que lhe assegura um império sobre si próprio. É também um lento: paciência, perseverança, estabilidade, ponderação, meditação, pessimismo, solidão ou melancolia. Se associarmos ao frio saturnino a secura marciana, temos o nervoso duro com a solidez da rocha: é um rude que beneficia dum sólido equilíbrio pelo domínio dos sentimentos e a firmeza do carácter: aprumo, sangue-frio, robustez, disciplina, obstinação, densidade, fixidez... Corresponde em caracterologia quer ao Fleumático: não Emotivo-Activo-Secundário, quer ao Apeixonado (Emotivo-Activo-Secundário), quer (o tipo inferior) ao Apático (não Emo92

tivo-não Activo-Secundário). A Secundaridade é uma constante da sua natureza, tão forte como a sua frieza natural. Dicléctica: Apresentam-se dois tipos opostos:

a) O ambicioso: Natureza caracterizada por uma áspera afirmação do eu ao serviço duma vontade de poder ou dum orgulho de dominação retraído. Arrivista ou ambicioso,

a sua libido tem uma sede de elevação. Tem possibilidades de se içar às alturas pela sua silenciosa e paciente obstinação, a sua previdência, a sua longa premeditação, a sua lucidez, a sua vontade bem empenhada; consegue-o tanto por um frio cálculo, uma maleabilidade diplomática à maneira da lâmina de aço, como pelo carácter indomável ou a, dureza do granito:

b) O Desapegado: A sua libido desapega-se do mundo terrestre, das cobiças e posses materiais; toma o caminho do despojamento. Trata-se por vezes duma ambição recalcada, revelada por uma humildade exagerada, um desinteresse excessivo, tormentos morais e escrúpulos dolorosos. Trata-se também duma ambição, mas toda moral, voltada para uma ascensão espiritual: ascese, contemplação, meditação, ou mesmo consagração total de si aos outros, ou ainda vida impessoal votada a uma grande obra, em encostas áridas que conduzem a cimos luminosos.

Destino: Geralmente, o começo da existência é difícil, pois o ser tem de vencer inibições e revela-se muito tardiamente. Mas sabe Tecuperar o tempo perdido com ia sua «disci lina, o seu ascetismo, a sua seriedade, o seu trabalho com afinco, É assim que sobe: lentamente mas com segurança, até aos postos de comando e de responsabilidade em que sabe tornar-se indispensável. As grandes horas da sua vida são muitas vezes numa idade avançada: é daqueles que fazem os grandes velhos. Mas a sua existência é por vezes austera, solitária ou retirada. g : :

Embora tenha o Sol, Mercúrio e Marte neste signo, Henrique IV é marcado primeiramente pela sua dominante Marte-Júpiter, « O conhecido carácter deste rei popular está nos antípodas do Oapricorniano clássico. No entanto os seus biógrafos são unânimes em distinguir neste monarca uma grande profundidade por trás da fachada duma natureza amena e ligeira. De facto, antes de: ser um grande estadista, foi um político superior que cedo teve o sentido dos acontecimentos complexos que se desenrolaram no país, agindo não no sentido de interesses imediatos mas em conformidade com uma ambição a longo prazo, como se tivesse preparado de longa

data o seu advento. Quando a morte surpreendeu Henrique TH, estava ele presente, pronto para assumir a sua sucessão. Não é apenas à sua assinatura planetária que deve esta robustez de gentil. “homem campónio de vontade rude. É também graças ao seu signo que este monarca viverá simplesmente, quase grosseiramente, desdenhando a etiqueta, numa vida campónia que contrastará singularmente com o fausto e a elegância dos Valois. Mas, uma vez no poder, este Capricorniano saberá restabelecer a autoridade do Estado, sentir-se-á senhor e estabelecerá a monarquia absoluta. Terá o culto da agricultura, garantirá a segurança dos campos, a protecção das colheitas e relançará a cultura sob a direcção de Olivier de Serres.`,
 10:`Simbólica: Simboliza na natureza a primeira assimilação da semente movamente semeada que se integra no meio terrestre, Este signo de Ar-Fixo não representa nem o vínculo do espírito dos Gémeos nem wo vínculo do coração da Balança, mas o da alma reve lado pelo mundo das afinidades electivas cujo resultado é o da fraternidade universal. Face ao Leão que personifica a realização do indivíduo cuja vontade está inteiramente ao serviço do Eu, o Aquário representa o acesso ao estádio superior da Pessoa pela aceitação de outrem e até ao destino à pertença universal. A tradição fez de Satumo o planeta regente deste signo: aqui, o dom saturnino não é mais um dever mas uma alegria, o desejo de perder-se uma realização. Depois da descoberta dos novos planetas, Urano é o seu segundo regente.

Psicologia: No oposto do Leão hercúleo, o Aquário serafim é duma natureza íntima «angélica» que pertence mais ao céu do que à terra, tendendo a libertar-se espontaneamente do peso dos elementos materiais e a afastar-se do instinto sentido como uma opacidade

contrária à sua natureza aérea, volátil, transparente, toda de limpidez espiritual. Tem o dom de desprender-se de si próprio, de desligar-se das suas pulsões instintivas a ponto de as ver como um estranho, pois a paixão toca-o mas não o perturba. O ódio foi banido do seu coração e tem a dom de se pôr à distância face às contingências materiais e das misérias da vida que não o atingem. Disso tira ele uma certa serenidade, uma harmonia de carácter, uma facilidade de viver e uma certa aspiração idealista e espiritual. A sua disposição afectiva fundamental é a oblatividade: o dom de si é um instinto seguro porque ele pertence não a si mas a outrem, sendo por excedência o homem do acolhimento, do conselho, do socorro; daí o sentido da amizade tão pronunciado nele. É muitas vezes pequeno de constituição, mas tem o dom de compensar uma. inferioridade física com uma superioridade intelectual, moral ou espiritual.

Dialéctica: Este tipo desemboca em duas vias segundo a sua dominante satumina ou uraniana:

a) A sabedoria: Esta tendência para pairar acima | das coisas afasta-o talvez do real (daí uma certa esquizoídia, mas é um ser saudável) mas permite-lhe atingir um certo ponto de altitude que responde à sua mecessidade de clareza e de ideal. Se não se perder na estranheza duma alma inquieta que flutua na vida por não se concretizar o suficiente, acha-se desligado, livre de tudo o que torna um ser espesso. Vive à margem do peso aprisionador do instinto, em direcção a esse mundo supra-sensível que ele povoa de imagens, de sensações, de visões. Consente em não mais se pertencer e em dar-se um destino extrapessoal feito de despossessão, de decantação, de purificação. Tomada duma grande desistência, esta graça ou esta sabedoria devolve-o à condição humana numa reconciliação do homem com o universo;

b) 4 aventura: Face à graça há o poder, O sonho subre-humano, a aventura prometaica. Este tipo vive num clima de alta tensão e tem uma louca sede de desmedida. Inadaptado, excêntrico, original ou revoltado — não quer ser como os outros—, é esse independente, esse individualista que aspira a evitar as sendas batidas, romper com a rotina e preconceitos, negligenciar as contingências, desprezar as convenções, empurrar os usos estabelecidos da moral e da sociedade. O que ele quer é a novidade, o modermismo, o «último grito». O que tenta é a revolução, o record, o frenesi, a necessidade de ir até aos limites extre95

mos do seu poder, de alargar infinitamente os limites do impossível, a busca do absoluto.

Destino: Muitas vezes a existência (para o segundo tipo sobre. tudo) é instável e pitoresca, não desprovida de contratempos e golpes de sorte inesperados. Em tal vida o que conta é menos o resultado material, ao qual o ser dedica um interesse por vezes excessivo, do que essa «experiência humana» que está empenhado em realizar. Não se trata de ser «alguém» mas sim «alguma coisa», tornando-se o servidor duma verdade ou duma necessidade social, muitas vezes como «progressista», como espírito de vanguarda, antecipador, revolucionário.
ando-se o servidor duma verdade ou duma necessidade social, muitas vezes como «progressista», como espírito de vanguarda, antecipador, revolucionário. Com o Sol e a Lua no Aquário, Carlos V é o próprio exemplo da compensação duma inferioridade física com uma superioridade moral. Dotado duma constituição frágil, sofre de uma saúde delicada a vida inteira, No entanto, precisa o seu biógrafo Joseph Calm «o facto notável é que essa vida, corporal tão penosa tenha po conciliar-se com uma das canreiras reais mais bem preenchidas. um contraste impressionante entre o físico e o moral de Carlos V O facto impõe-se à meditação. Nenhum personagem da história infligiu um tão peremptório desmentido ao determinismo que quer subordinar o moral ao físico e a alma ao corpo. Apesar da sua saúde vacilante, o seu aspecto impunha-se, e sobretudo a sua igual. | dade de humor, a sua serenidade, que resgatavam aos olhos dos súbditos as deficiências do temperamento 3. » Este príncipe não tinha todavia mem o instante mordente dum Carneiro como Napoleão HI, mem a paixão opiniosa dum Touro como Catarina, nem o poder voluntarioso dum Leão como Napoleão, nem tão-pouco a co) tividade dum Escorpião como Luís XI. A sua subtil eficácia res;
ro como Catarina, nem o poder voluntarioso dum Leão como Napoleão, nem tão-pouco a co) tividade dum Escorpião como Luís XI. A sua subtil eficácia res; inteiramente na «bela maneira de viver comedidamente em todas as coisas», como nos diz Christine de Pisan. Merecendo bem o cognome de sábio, soube rodear-se duma equipa de homens competentes, soube cativá-los e utilizar as suas capacidades, não receando confiar o seu exército ao mais capaz, embora de origem modesta: Bertrand Du Guesclin. Este rei que «reinou para o bem comum do povo, não para 0 seu proveito próprio e singular», só pode pertenc: a um Aquário quando declara apoiar-se essencialmente neste preceito de Aristóteles: «A maioria em que cada membro não é um homem notável está no entanto acima de todos os homens superiores.» Em vão procuramos em Luís XV a mota do Sol-Aquário, sem dúvida. apagada pela sua impressionante dominante planetária. Em compen5 JOSEPH CALMETTE, Charles V, p. 213, Arthéme Fayard, 1945.`,
 11:`Simbólica: Simboliza na natureza esse estado transitório entre o Inverno que acaba e a Primavera que se prepara, mundo do impreciso onde tudo permanece no informe, sem fronteiras bem traçadas. A Agua-Mutável que representa é tanto as cheias invermais, dilúvio purificador em que os laços são desatados, as forças de coesão apagadas, como a massa móvel e anónima das águas marinhas em que tudo se precipita, a imensidão oceânica. Água dissolvente, mas também água fecundante, de que os fundos inesgotáveis do meio marinho são o exemplo. Face à Virgem que põe O acento no pormenor, no particular, no limite, no preciso, na norma, na regra, na medida..., os Peixes aparecem como o mundo do comjunto, do global, do ilimitado, do infinito, do virtual, do latente, do inclassificável, do inapreensível, do inefável... onde o irracional e o sobrerracional reinam indivisos. É a grande comunidade... Aí Teinam os astros de fecundidade: Júpiter está em domicílio e Vénus exaltada. Arquétipo da dissolução e da integração universais, Neptuno figura como novo regente.

Psicologia: A trama profunda deste tipo é uma plasticidade psíquica excepcional: mialeabilidade, impressionabilidade, vulnerabilidade, receptividade, procura duma inflação emotiva, duma excepcional dilatação do ser, feito para a participação com o grande Todo. Esta disposição tem a ver ao mesmo tempo com um desejo de escapar ao mundo da limitação pela evasão, com a frequentação do infra e do ultra das coisas e dos seres, com uma imaginação difluente que se derrama, se espraia até ao infinito, e com uma emplitude do campo de consciência que se junta à flutuação, à flexibilidade e ao espraiamento do ser, rolando a consciência uma massa ide impressões muitas vezes difusas. Este proteico está, pois, em potência de dilatação e de fusão. A sua dificuldade é fazer deste

tico caos um mundo organizado, sem o que se arrisca a permanecer uma nebulosa, um ser que se procura, apalpa, foge de si próprio, que «flutua» ou nada entre duas águas, indeciso, irresoluto, veleitário, fugidio e impossível de captar, instável, errante, confuso, atamancado, quimérico, incoerente... Realizando a sua unidade interior pela afirmação do Eu, este tipo fica em condições de viver um estado de graça, de clarividência, de santidade ou de misticidade, e de dar toda a sua medida de bondade, generosidade e humanidade, revelando-se no desinteressado esquecimento de si ou mesmo no sacrifício redentor. Conhece o fervor da vida profunda e é capaz dos maiores encantos da alma.

Dialéctica: Como para cada tipo zodiacal, revelam-se duas orientações que podem coexistir apesar da sua aparente contradiç
maiores encantos da alma.

a) O extremo dilatado: O Eu aspira a um surto cósmico, por sede de grande evasão, duma grande dimensão. É como que o nómada que não tem pátria, não possui nada ma Terra e abandona-se a todos os horizontes. Iça a vela em direcção às brumas longínquas para alcançar regiões desconhecidas. Trata-se dum impulso vital em direcção ao infinito ou a uma totalidade o mais vasta possível. Cosmopolita, internacionalista, comunitário ou místico, tem, necessidade de alcançar o vasto universo para com ele se confundir; a g a

b) O extremo concentrado: Este Peixe também pode ser cativo dalguma rede ou permanecer no asilo da sua ilhota. Prisioneiro dum pequeno espaço, arrisca-se a encalhar nas costas dum mundo da provação que é o duma, prisão, dum cativeiro ou dum exílio interior, senão mesmo exterior.

Destino: Existência instável e por vezes caótica, que se deve preservar dos sonhos impotentes, dos projectos quiméricos, das utópicas esperanças e outros edifícios grandiosos construídos sobre o nada... embora não estejam excluídas do seu jogo as «pescas milagrosas». Muitas vezes a sua realização, de ordem moral e espiritual, só começa a partir do consentimento em esquecer-se, em perder-se, em sacrificar-se, mas então ele conhece, pelo dom, a fecundidade ou a alegria,

O único rei com qualidade de Peixes, e que o é duplamente pela presença do Sol e da Lua no signo, é Carlos VII: «Na verdade, Carlos [...] continua a ser à primeira impressão o Misterioso, Nele tudo é turvo, por vezes inexplicável: o seu nascimento, o seu carácter, a evolução da sua personalidade, a sua atitude relativamente a um destino instável, as suas acções nobres e as suas acções baixas, 05

seus amores, os seus triunfos, a sua morte. Revela-se, segundo as ocasiões, cobarde ou valente, sibarita ou laborioso, neurótico ou
ICO DE ASTROLOGIA

do-o um «Delfim por assim dizer», e quando o seu pai, Carlos VI, o declara «parricida, criminoso de lesa-majestade, inimigo da coisa pública, de Deus. », está condenado à situação do Peixes «concentrado»: bastando, prosorito, banido, como se o papel de refém consentinte dos seus partidiários não lhe tivesse bastado, Recluso no fundo dos seus quartinhos do seu obscuro castelo de Loches, o «mutável e dissidente» Regente do reino vive como que num estado de hipnose em face duma situação dupla tipicamente Peixes: a França possui então dois sobeanos, dois parlamentos, duas Câmaras de Contas, duas moedas, dois conselhos da coroa, igualmente desunidos! Carregado de correntes pelas recordações da sua primeira mocidade, pela sua instabilidade E 06 seus casos de consciência, oprimido pelo peso da sua fraqueza, deslizando ao sabor duma voluptuosa preguiça, condenado à cobardia, por toda a parte bate em retirada, fugindo em combate e diante de si mesmo, e até depondo por vezes as armas antes de se servir delas. É que duvida de si, do seu nascimento, do seu direito, dos Seus servidores e da eficácia da luta que tem de travar; vêmo-lo, como um destroço, errar em busca de si mesmo. Mas havia de Tealizar-se neste príncipe uma verdadeira e imprevisível metamorfose.
m de travar; vêmo-lo, como um destroço, errar em busca de si mesmo. Mas havia de Tealizar-se neste príncipe uma verdadeira e imprevisível metamorfose. No fundo da sua prisão velava um neto de Carlos V, e Carlos VII (por razões que mais adiante veremos), tornando-se vitorioso de si mesmo, tornou-se vitorioso do inimigo e apresentou-se finalmente à posteridade como um rei digno da melhor tradição.`,
};
